<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Yita.Native.Windows</AssemblyName>
    <RootNamespace>Yita.Native.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Yita.Core\Yita.Core.csproj" />
  </ItemGroup>
</Project>
