<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Yita.Core</AssemblyName>
    <RootNamespace>Yita.Core</RootNamespace>
    <Version>0.9.0</Version>
  </PropertyGroup>
  <Import Project="Parity/OriginalBehavior.props" />
</Project>
